# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City1',
            fields=[
                ('city_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.City')),
                ('names', models.CharField(max_length=20)),
            ],
            bases=('myapp.city',),
        ),
    ]
