# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_city1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city1',
            name='city_ptr',
        ),
        migrations.DeleteModel(
            name='City1',
        ),
    ]
